# Generated by Django 3.2.5 on 2022-08-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_dimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimg',
            name='did',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimg',
            name='img_url',
            field=models.ImageField(upload_to='img'),
        ),
    ]
